"""상품 API 모델 모음"""

# Base models (공통)
from .base import (
    CartInfo,
    CommissionInfo,
    ImmediateDiscountInfo,
    MaxBuyCountInfo,
    MemberGradeDisplayInfo,
    MemberGroupDisplayInfo,
    PlatformDisplayInfo,
    PromotionInfo,
    PromotionTextInfo,
    SalePeriodInfo,
)

# 변경된 상품 번호 목록 조회
from .changed import (
    ChangedProductItem,
    ChangedProductsResponse,
)

# 상품 상세 조회 V1
from .detail_v1 import (
    ProductDetailV1Response,
    V1AccumulationLimitInfo,
    V1CustomPropertyValue,
    V1DisplayCategory,
    V1ImageUrlMappingInfo,
    V1MallProduct,
    V1MallProductImage,
    V1MallProductInput,
    V1MallProductOption,
    V1MappingOption,
    V1OptionImage,
    V1RefundableInfo,
    V1RelatedProductInfo,
    V1ReservationInfo,
    V1Sticker,
    V1StickerDisplayPeriod,
)

# 상품 상세 조회 V3
from .detail_v3 import (
    MallProductImage,
    OptionImage,
    OptionMapping,
    ProductDetailV3Response,
    ProductOption,
)

# 상품 리스트 검색
from .list_search import (
    AdditionalDiscount,
    CategoryInfo,
    Commission,
    CustomerDemand,
    CustomProperty,
    DeliveryInfo,
    DiscountInfo,
    ImmediateDiscount,
    Limitations,
    ListSearchCartInfo,
    ListSearchDisplayCategory,
    ListSearchOptionImage,
    ProductImage,
    ProductListItem,
    ProductListSearchResponse,
    ProductOptionDetail,
    ProductStock,
    SaleInfo,
    SalePeriod,
    Sticker,
)

# 상품 수정 V2
from .patch_v2 import (
    PatchAccumulationLimitInfo,
    PatchBrandInfo,
    PatchBrandNameInfo,
    PatchBrandNoInfo,
    PatchCartInfo,
    PatchCommissionInfo,
    PatchContentDetail,
    PatchCustomerDemand,
    PatchCustomProperty,
    PatchDeliveryInfo,
    PatchDisplayInfo,
    PatchDutyContent,
    PatchExtraJson,
    PatchImageInfo,
    PatchImmediateDiscountInfo,
    PatchListImage,
    PatchMarketingDisplayPeriod,
    PatchMarketingInfo,
    PatchMarketingPhraseInfo,
    PatchMaxBuyQuantityInfo,
    PatchMemberDisplayInfo,
    PatchOption,
    PatchOptionImage,
    PatchOptionInfo,
    PatchPlaceOriginInfo,
    PatchPlatformDisplayInfo,
    PatchPriceInfo,
    PatchProductGuide,
    PatchProductImage,
    PatchProductV2Request,
    PatchPurchaseLimitQuantity,
    PatchRefundableInfo,
    PatchRelatedProductInfo,
    PatchSalePeriod,
    PatchSalePeriodInfo,
    PatchSticker,
    PatchStickerDisplayPeriod,
    PatchUnavailablePeriod,
    PatchUnitPriceInfo,
)

# 상품 검색 V2
from .search_v2 import (
    AccumulationInfo,
    CertificationData,
    CertificationInfo,
    DisplayCategory,
    DisplayPeriod,
    HasCoupons,
    OptionValue,
    ProductSearchItem,
    ProductSearchV2Response,
    ReservationData,
    StickerInfo,
)

__all__ = [
    # Base
    "CartInfo",
    "CommissionInfo",
    "ImmediateDiscountInfo",
    "MaxBuyCountInfo",
    "MemberGradeDisplayInfo",
    "MemberGroupDisplayInfo",
    "PlatformDisplayInfo",
    "PromotionInfo",
    "PromotionTextInfo",
    "SalePeriodInfo",
    # Changed
    "ChangedProductItem",
    "ChangedProductsResponse",
    # Detail V1
    "ProductDetailV1Response",
    "V1AccumulationLimitInfo",
    "V1CustomPropertyValue",
    "V1DisplayCategory",
    "V1ImageUrlMappingInfo",
    "V1MallProduct",
    "V1MallProductImage",
    "V1MallProductInput",
    "V1MallProductOption",
    "V1MappingOption",
    "V1OptionImage",
    "V1RefundableInfo",
    "V1RelatedProductInfo",
    "V1ReservationInfo",
    "V1Sticker",
    "V1StickerDisplayPeriod",
    # Detail V3
    "MallProductImage",
    "OptionImage",
    "OptionMapping",
    "ProductDetailV3Response",
    "ProductOption",
    # List Search
    "AdditionalDiscount",
    "CategoryInfo",
    "Commission",
    "CustomerDemand",
    "CustomProperty",
    "DeliveryInfo",
    "DiscountInfo",
    "ImmediateDiscount",
    "Limitations",
    "ListSearchCartInfo",
    "ListSearchDisplayCategory",
    "ListSearchOptionImage",
    "ProductImage",
    "ProductListItem",
    "ProductListSearchResponse",
    "ProductOptionDetail",
    "ProductStock",
    "SaleInfo",
    "SalePeriod",
    "Sticker",
    # Patch V2
    "PatchAccumulationLimitInfo",
    "PatchBrandInfo",
    "PatchBrandNameInfo",
    "PatchBrandNoInfo",
    "PatchCartInfo",
    "PatchCommissionInfo",
    "PatchContentDetail",
    "PatchCustomerDemand",
    "PatchCustomProperty",
    "PatchDeliveryInfo",
    "PatchDisplayInfo",
    "PatchDutyContent",
    "PatchExtraJson",
    "PatchImageInfo",
    "PatchImmediateDiscountInfo",
    "PatchListImage",
    "PatchMarketingDisplayPeriod",
    "PatchMarketingInfo",
    "PatchMarketingPhraseInfo",
    "PatchMaxBuyQuantityInfo",
    "PatchMemberDisplayInfo",
    "PatchOption",
    "PatchOptionImage",
    "PatchOptionInfo",
    "PatchPlaceOriginInfo",
    "PatchPlatformDisplayInfo",
    "PatchPriceInfo",
    "PatchProductGuide",
    "PatchProductImage",
    "PatchProductV2Request",
    "PatchPurchaseLimitQuantity",
    "PatchRefundableInfo",
    "PatchRelatedProductInfo",
    "PatchSalePeriod",
    "PatchSalePeriodInfo",
    "PatchSticker",
    "PatchStickerDisplayPeriod",
    "PatchUnavailablePeriod",
    "PatchUnitPriceInfo",
    # Search V2
    "AccumulationInfo",
    "CertificationData",
    "CertificationInfo",
    "DisplayCategory",
    "DisplayPeriod",
    "HasCoupons",
    "OptionValue",
    "ProductSearchItem",
    "ProductSearchV2Response",
    "ReservationData",
    "StickerInfo",
]
