"""Order Friends API 클라이언트 패키지 (통계/정산/CS)"""

from shopby_sdk.clients.order_friends.client import ShopbyServerOrderFriendsApiClient
from shopby_sdk.clients.order_friends.models import (
    CouponType,
    CsAudit,
    CsChannelType,
    CsItem,
    CsPathType,
    CsResponse,
    CsStatusType,
    CsType,
    GenderType,
    MemberJoinType,
    MemberType,
    OrdersSalesCouponInfo,
    OrdersSalesItem,
    OrdersSalesMemberGroupInfo,
    OrdersSalesMemberInfo,
    OrdersSalesPaymentInfo,
    OrdersSalesPriceInfo,
    OrdersSalesProductInfo,
    OrdersSalesResponse,
    OrdersSalesSetOption,
    PayType,
    PlatformType,
    ProductKeywordType,
    ProductType,
    PromotionKeywordType,
    SaleMethodType,
    SettlementDetailItem,
    SettlementDetailResponse,
    SettlementItem,
    SettlementPartnerType,
    StatisticsPromotionCoupon,
    StatisticsPromotionDetailItem,
    StatisticsPromotionsResponse,
    StatisticsSalesPeriodItem,
    StatisticsSalesPeriodResponse,
    StatisticsSalesProductItem,
    StatisticsSalesProductResponse,
    StatisticsSalesPromotionSummary,
    StatisticsSalesSummary,
    StatisticsSalesSummaryResponse,
)

__all__ = [
    "ShopbyServerOrderFriendsApiClient",
    # Literal 타입 별칭
    "CsType",
    "CsChannelType",
    "CsStatusType",
    "CsPathType",
    "SettlementPartnerType",
    "CouponType",
    "GenderType",
    "MemberJoinType",
    "MemberType",
    "PlatformType",
    "PromotionKeywordType",
    "ProductKeywordType",
    "ProductType",
    "SaleMethodType",
    "PayType",
    # CS
    "CsAudit",
    "CsItem",
    "CsResponse",
    # Orders Sales
    "OrdersSalesMemberGroupInfo",
    "OrdersSalesMemberInfo",
    "OrdersSalesSetOption",
    "OrdersSalesProductInfo",
    "OrdersSalesPriceInfo",
    "OrdersSalesPaymentInfo",
    "OrdersSalesCouponInfo",
    "OrdersSalesItem",
    "OrdersSalesResponse",
    # Settlement
    "SettlementItem",
    "SettlementDetailItem",
    "SettlementDetailResponse",
    # Statistics - Promotions
    "StatisticsPromotionCoupon",
    "StatisticsPromotionsResponse",
    "StatisticsPromotionDetailItem",
    # Statistics - Sales
    "StatisticsSalesPeriodItem",
    "StatisticsSalesPeriodResponse",
    "StatisticsSalesProductItem",
    "StatisticsSalesProductResponse",
    "StatisticsSalesSummary",
    "StatisticsSalesPromotionSummary",
    "StatisticsSalesSummaryResponse",
]
