"""Promotion(쿠폰) API 클라이언트 패키지"""

from shopby_sdk.clients.promotion.client import ShopbyServerPromotionApiClient
from shopby_sdk.clients.promotion.models import (
    CartCouponDetail,
    CouponDetailResponse,
    CouponDiscount,
    CouponIssueContent,
    CouponIssueSearchDateType,
    CouponSearchDateType,
    CouponSearchKeywordType,
    CouponStatusType,
    CouponSubType,
    CouponSummary,
    CouponTargetContent,
    CouponTargetItem,
    CouponTargetsResponse,
    CouponTargetType,
    CouponType,
    CouponUseSearchDateType,
    CouponUseSearchKeywordType,
    CreateCouponRequest,
    CreateCouponResponse,
    GiftCouponDetail,
    GiftCouponType,
    IssuableConstraint,
    IssueCouponRequest,
    IssueCouponResult,
    IssueType,
    PayType,
    PlatformType,
    ProductCouponDetail,
    RollbackCouponRequest,
    SearchCouponContent,
    SearchCouponIssueResponse,
    SearchCouponResponse,
    UpdateCouponRequest,
    UsableConstraint,
    UsedCouponContent,
    UseCouponItem,
    UseStopCouponRequest,
    WithdrawCouponBulkRequest,
    WithdrawCouponRequest,
)

__all__ = [
    "ShopbyServerPromotionApiClient",
    # Literal 타입 별칭
    "CouponType",
    "CouponSubType",
    "IssueType",
    "CouponStatusType",
    "CouponTargetType",
    "PlatformType",
    "GiftCouponType",
    "PayType",
    "CouponSearchDateType",
    "CouponSearchKeywordType",
    "CouponIssueSearchDateType",
    "CouponUseSearchDateType",
    "CouponUseSearchKeywordType",
    # 응답 모델
    "SearchCouponResponse",
    "SearchCouponContent",
    "CouponTargetsResponse",
    "CouponTargetContent",
    "UsedCouponContent",
    "SearchCouponIssueResponse",
    "CouponIssueContent",
    "IssueCouponResult",
    "CreateCouponResponse",
    "CouponDetailResponse",
    # 중첩 구성요소
    "CouponTargetItem",
    "CartCouponDetail",
    "ProductCouponDetail",
    "GiftCouponDetail",
    "UsableConstraint",
    "IssuableConstraint",
    "CouponDiscount",
    "CouponSummary",
    # 요청 모델
    "CreateCouponRequest",
    "UpdateCouponRequest",
    "IssueCouponRequest",
    "UseCouponItem",
    "WithdrawCouponRequest",
    "WithdrawCouponBulkRequest",
    "RollbackCouponRequest",
    "UseStopCouponRequest",
]
