"""Member API 클라이언트 및 모델"""

from shopby_sdk.clients.member.client import ShopbyServerMemberApiClient
from shopby_sdk.clients.member.models import (
    AddMemberToGroupRequest,
    AddMemberToGroupResponse,
    AppCardStoreIdRequest,
    AppleLoginConfig,
    BlockedReleaseRequest,
    BulkDeleteProfileRequest,
    CommonJoinConfigResponse,
    DormantMemberContent,
    DormantMemberInner,
    DormantMembersResponse,
    DormantReleaseRequest,
    ExpelledMember,
    ExternalMemberIdUpdateRequest,
    ExternalMemberRequest,
    ExternalMemberResponse,
    ExtraInfoConfigResponse,
    ExtraInfoOptionSummary,
    ExtraInfoSummaryContent,
    Grade,
    GradeImage,
    GradeUpdateMember,
    JoinConfigItemStatus,
    JoinTermsAgreementType,
    Member,
    MemberGroup,
    MemberGroupRequest,
    MemberProhibitRequest,
    MemberProhibitResponse,
    MemberProhibitResultRow,
    MemberSearchType,
    MembersListResponse,
    MemberStatus,
    MemberType,
    NotificationType,
    OpenIdConfigResponse,
    OpenIdConfigUpdateRequest,
    OpenIdProvider,
    PendingProviderAction,
    PendingProviderRequest,
    ProfileAgreedTerms,
    ProfileCustomAgreedTerms,
    ProfileExtraInfo,
    ProfileExtraInfoRequest,
    ProfileGradesRequest,
    ProfileGradesResponse,
    ProfileGroupItem,
    ProfileGroupsResponse,
    ProfileMemberGroup,
    ProfileResponse,
    ProfileBulkUpdateResponse,
    ProfileUpdateRequest,
    ProfileUpdateResponse,
    ProhibitStatus,
    ProviderType,
    ReserveBenefit,
)

__all__ = [
    # Client
    "ShopbyServerMemberApiClient",
    # Request Enum Types
    "MemberSearchType",
    "MemberStatus",
    "MemberType",
    "ProviderType",
    "JoinConfigItemStatus",
    "PendingProviderAction",
    "ProhibitStatus",
    "NotificationType",
    "JoinTermsAgreementType",
    # Member Group Models
    "ReserveBenefit",
    "MemberGroup",
    "MemberGroupRequest",
    # Profile Group Models
    "ProfileGroupItem",
    "ProfileGroupsResponse",
    "AddMemberToGroupRequest",
    "AddMemberToGroupResponse",
    # Member Models
    "OpenIdProvider",
    "Member",
    "MembersListResponse",
    "ExpelledMember",
    # Configuration Models
    "CommonJoinConfigResponse",
    "ExtraInfoConfigResponse",
    "ExtraInfoSummaryContent",
    "ExtraInfoOptionSummary",
    "OpenIdConfigResponse",
    "OpenIdConfigUpdateRequest",
    "AppleLoginConfig",
    "AppCardStoreIdRequest",
    "PendingProviderRequest",
    # Grade Models
    "Grade",
    "GradeImage",
    "ProfileGradesRequest",
    "ProfileGradesResponse",
    "GradeUpdateMember",
    # External Member Models
    "ExternalMemberRequest",
    "ExternalMemberResponse",
    "ExternalMemberIdUpdateRequest",
    # Prohibit Models
    "MemberProhibitRequest",
    "MemberProhibitResponse",
    "MemberProhibitResultRow",
    # Profile Models
    "ProfileResponse",
    "ProfileMemberGroup",
    "ProfileAgreedTerms",
    "ProfileCustomAgreedTerms",
    "ProfileExtraInfo",
    "ProfileExtraInfoRequest",
    "ProfileUpdateRequest",
    "ProfileUpdateResponse",
    "ProfileBulkUpdateResponse",
    "BulkDeleteProfileRequest",
    "BlockedReleaseRequest",
    # Dormant Models
    "DormantMembersResponse",
    "DormantMemberContent",
    "DormantMemberInner",
    "DormantReleaseRequest",
]
