"""Shopby Shop(Client) Admin API.

shop-api(`https://shop-api.e-ncp.com`) 의 Mall(몰 기본 정보) 공개 엔드포인트.
"""

from shopby_sdk.shop.admin.client import ShopbyShopAdminApiClient
from shopby_sdk.shop.admin.models import (
    AccumulationConfig,
    BankAccountInfo,
    BankType,
    BoardCategory,
    BoardsCategory,
    Categories,
    CartConfig,
    Currency,
    EscrowLogo,
    ExternalServiceConfig,
    FlatCategory,
    GlobalMallHierarchy,
    GlobalSubMallSummary,
    GradeCoupon,
    GradeEvaluationCondition,
    GradeReserveAutoSupplying,
    GradeReserveBenefit,
    I18nConfig,
    InquiryType,
    IntroRedirection,
    KakaoMap,
    LabelValue,
    Mall,
    MallGrade,
    MallInternationalizationResponse,
    MallJoinConfig,
    MallPartner,
    MallResponse,
    MallSsl,
    MallUrl,
    MemberJoinConfig,
    MultiLevelCategory,
    OpenIdJoinConfig,
    ReviewsAccumulationDetail,
    ServiceBasicInfoResponse,
    ServiceCenter,
    TermsConfig,
)

__all__ = [
    "ShopbyShopAdminApiClient",
    # /malls
    "MallResponse",
    "Mall",
    "MallUrl",
    "ServiceCenter",
    "IntroRedirection",
    "EscrowLogo",
    "GlobalMallHierarchy",
    "GlobalSubMallSummary",
    "MallGrade",
    "GradeEvaluationCondition",
    "GradeReserveAutoSupplying",
    "GradeReserveBenefit",
    "GradeCoupon",
    "InquiryType",
    "LabelValue",
    "BankType",
    "BankAccountInfo",
    "MemberJoinConfig",
    "MallJoinConfig",
    "OpenIdJoinConfig",
    "AccumulationConfig",
    "ReviewsAccumulationDetail",
    "CartConfig",
    "KakaoMap",
    "ExternalServiceConfig",
    "TermsConfig",
    "Categories",
    "FlatCategory",
    "MultiLevelCategory",
    "BoardsCategory",
    "BoardCategory",
    # /malls/internationalization
    "MallInternationalizationResponse",
    "Currency",
    "I18nConfig",
    # /malls/partners
    "MallPartner",
    # /malls/ssl
    "MallSsl",
    # /malls/service-basic-info
    "ServiceBasicInfoResponse",
]
